name: Docker Image CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag anushibin007/insta-reel-cropper:latest
            - name: Push the Docker image
              run: docker login -u anushibin007 -p ${{ secrets.DOCKER_TOKEN }} && docker push ijn35807/docker-image-autobuild:latest
